/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: martinMCGREGOR (https://sketchfab.com/martinMCGREGOR)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/physics-3december-day-16-86e60cd6b1b946f1a9e9ba294097cbcd
Title: Physics: 3december day 16
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useMotionValue, useSpring } from 'motion/react'
import { useFrame } from '@react-three/fiber';

export function Atom(props) {
    const group = useRef();
    const { nodes, materials } = useGLTF('/models/physics_3december_day_16.glb')

    const yPosition = useMotionValue(5);
    const ySpring = useSpring(yPosition, {damping: 30});
    useEffect(() => {
        ySpring.set(-1);
    }, [ySpring]);
    useFrame(() => {
        group.current.position.y = ySpring.get();
    })
    return (
        <group
            ref={group} 
            {...props} 
            dispose={null}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={props.scale || 0.2}
            position={props.position || [1.3, -1, 0]}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_2.geometry}
                material={materials['Material.001']}
            />
        </group>
    )
}

useGLTF.preload('/models/physics_3december_day_16.glb')